"""initial schema

Revision ID: 428534d6a348
Revises: 
Create Date: 2026-10-06 02:43:30.902760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '428534d6a348'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('jurisdiction_level', sa.String(), nullable=False),
    sa.Column('jurisdiction_geo', sa.String(), nullable=True),
    sa.Column('codebook_title', sa.String(), nullable=True),
    sa.Column('domain', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('agency_id')
    )
    op.create_table('code_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('citation', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('jurisdiction_level', sa.String(), nullable=False),
    sa.Column('jurisdiction_geo', sa.String(), nullable=True),
    sa.Column('title_number', sa.String(), nullable=True),
    sa.Column('part', sa.String(), nullable=True),
    sa.Column('section_number', sa.String(), nullable=True),
    sa.Column('heading', sa.String(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('owning_agency', sa.String(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('amendment_source', sa.String(), nullable=True),
    sa.Column('prior_version_id', sa.Integer(), nullable=True),
    sa.Column('superseded_by', sa.String(), nullable=True),
    sa.Column('repealed_date', sa.Date(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prior_version_id'], ['code_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'citation', 'snapshot_date', name='uq_code_section_key')
    )
    op.create_index('ix_code_section_lookup', 'code_sections', ['source_system', 'citation'], unique=False)
    op.create_table('regulatory_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('jurisdiction_level', sa.String(), nullable=False),
    sa.Column('jurisdiction_geo', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('action_text', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('agency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('date_published', sa.Date(), nullable=True),
    sa.Column('date_effective', sa.Date(), nullable=True),
    sa.Column('date_comment_close', sa.Date(), nullable=True),
    sa.Column('date_filed', sa.Date(), nullable=True),
    sa.Column('docket_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('rin', sa.String(), nullable=True),
    sa.Column('cfr_references', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('legal_refs', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('affected_entities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('related_actions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('full_text_url', sa.String(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('adapter_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'source_id', name='uq_regulatory_action_key')
    )
    op.create_index('ix_regulatory_action_agency', 'regulatory_actions', ['source_system', 'agency'], unique=False)
    op.create_index('ix_regulatory_action_date_published', 'regulatory_actions', ['date_published'], unique=False)
    op.create_index('ix_regulatory_action_status', 'regulatory_actions', ['status'], unique=False)
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('cursor_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system')
    )
    op.create_table('action_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_action_id', sa.Integer(), nullable=False),
    sa.Column('to_action_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_action_id'], ['regulatory_actions.id'], ),
    sa.ForeignKeyConstraint(['to_action_id'], ['regulatory_actions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_action_id', 'to_action_id', 'relationship_type', name='uq_action_relationship')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_relationships')
    op.drop_table('sync_state')
    op.drop_index('ix_regulatory_action_status', table_name='regulatory_actions')
    op.drop_index('ix_regulatory_action_date_published', table_name='regulatory_actions')
    op.drop_index('ix_regulatory_action_agency', table_name='regulatory_actions')
    op.drop_table('regulatory_actions')
    op.drop_index('ix_code_section_lookup', table_name='code_sections')
    op.drop_table('code_sections')
    op.drop_table('agencies')
    # ### end Alembic commands ###
